// <auto-generated />
using System;
using CampEventos.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CampEventos.Persistence.Migrations
{
    [DbContext(typeof(CampEventosContext))]
    [Migration("20260512110034_Inittial")]
    partial class Inittial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CampEventos.Domain.Apresentador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiniCurriculo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apresentadores");
                });

            modelBuilder.Entity("CampEventos.Domain.ApresentadorEvento", b =>
                {
                    b.Property<int>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApresentadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventoId", "ApresentadorId");

                    b.HasIndex("ApresentadorId");

                    b.ToTable("ApresentadoresEventos");
                });

            modelBuilder.Entity("CampEventos.Domain.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataEvento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdPessoas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tema")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("CampEventos.Domain.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preço")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("CampEventos.Domain.RedeSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApresentadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApresentadorId");

                    b.HasIndex("EventoId");

                    b.ToTable("RedesSociais");
                });

            modelBuilder.Entity("CampEventos.Domain.ApresentadorEvento", b =>
                {
                    b.HasOne("CampEventos.Domain.Apresentador", "Apresentador")
                        .WithMany("ApresentadoresEventos")
                        .HasForeignKey("ApresentadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampEventos.Domain.Evento", "Evento")
                        .WithMany("ApresentadoresEventos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apresentador");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("CampEventos.Domain.Lote", b =>
                {
                    b.HasOne("CampEventos.Domain.Evento", "Evento")
                        .WithMany("Lotes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("CampEventos.Domain.RedeSocial", b =>
                {
                    b.HasOne("CampEventos.Domain.Apresentador", "Apresentador")
                        .WithMany("RedesSociais")
                        .HasForeignKey("ApresentadorId");

                    b.HasOne("CampEventos.Domain.Evento", "Evento")
                        .WithMany("RedeSociais")
                        .HasForeignKey("EventoId");

                    b.Navigation("Apresentador");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("CampEventos.Domain.Apresentador", b =>
                {
                    b.Navigation("ApresentadoresEventos");

                    b.Navigation("RedesSociais");
                });

            modelBuilder.Entity("CampEventos.Domain.Evento", b =>
                {
                    b.Navigation("ApresentadoresEventos");

                    b.Navigation("Lotes");

                    b.Navigation("RedeSociais");
                });
#pragma warning restore 612, 618
        }
    }
}
